### ISSUE TITLE
Hello, thank you for your contribution, now I want to try the effect of the paper, do this code are the code implemented in the paper?

### ISSUE THREAD

**Issue by wanjh1024** [tengyu1998/SCI#1]

**Comment by tengyu1998** [comment]
您好，邮件已收到，我将尽快处理。

**Comment by tengyu1998** [comment]
Thanks for your interest. This is the preliminary code, we will update the code in the next days.

**Comment by wanjh1024** [comment]
> Thanks for your interest. This is the preliminary code, we will update the code in the next days.

Get it.Thanks for your reply.
