### ISSUE TITLE
About the license of this repository.

### ISSUE THREAD

**Issue by Kazuhito00** [tengyu1998/SCI#2]
Thank you for sharing your wonderful achievements.
What is the license for this repository?

**Comment by tengyu1998** [comment]
您好，邮件已收到，我将尽快处理。

**Comment by spiegelball** [comment]
Hey, I am also interested in which license this project has. Unfortunately I can't translate the last comment, song any statement in English would be appreciated! Thank you :)

**Comment by tengyu1998** [comment]
您好，邮件已收到，我将尽快处理。

**Comment by tengyu1998** [comment]
This project is released under the MIT license.

**Comment by Kazuhito00** [comment]
Thank you for answering.
