### ISSUE TITLE
The evaluate results on LOL datasets seems not well as reported in the paper

### ISSUE THREAD

**Issue by JuZiSYJ** [tengyu1998/SCI#3]
![image](https://user-images.githubusercontent.com/38501523/164714890-7546c02d-1bbb-4e84-b64e-0de1eca7af2e.png)
![image](https://user-images.githubusercontent.com/38501523/164715037-9dce2c76-8282-41bb-8a35-98940fa06370.png)
The results produced by provided weight seem not good enough..

**Comment by tengyu1998** [comment]
The provided model file is trained on MIT dataset. We will update the models on other benchmarks soon.

**Comment by JuZiSYJ** [comment]
Thanks a lot！

**Comment by doctorimage** [comment]
evaluate results  seems not well as reported in the paper!
<img width="1255" alt="12" src="https://user-images.githubusercontent.com/2292481/165003541-b9d117f2-7a6d-476f-84d1-8a9112035256.png">
<img width="1325" alt="14" src="https://user-images.githubusercontent.com/2292481/165003546-9cc0b9b9-220b-4024-a11c-60afa8d6c9e9.png">
<img width="2171" alt="18" src="https://user-images.githubusercontent.com/2292481/165003548-b6cb312b-817e-469e-8a4a-f30598ed808c.png">

**Comment by tengyu1998** [comment]
Hi, thanks for your interest in this project. In fact, model trained on one dataset does not perform well on other data. We will update the training code soon so you can retrain on your data.

**Comment by doctorimage** [comment]
I sent dozens of test pictures, which are very common pictures in low light
Especially the lamp


Tengyu Ma ***@***.***> 于2022年4月25日周一 10:36写道：

**Comment by HuangHW012** [comment]
> Thanks a lot！

Did you evaluate results on LOL datasets well?

**Comment by tengyu1998** [comment]
您好，邮件已收到，我将尽快处理。

**Comment by HuangHW012** [comment]
您好，事实上我尝试用Tensorflow 2实现您们的模型，可是表现不甚理想，请问我可以分享我实现的代码吗？可能是我代码写错导致预测环节出问题！

(训练跟测试都在LOL dataset，且不包含finetune model)

万分感谢！

Tengyu Ma ***@***.***> 於 2022年6月5日 週日 下午3:34 寫道：
